# Generated by Django 4.0.4 on 2022-05-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.IntegerField(default=1000, verbose_name='Баланс'),
        ),
    ]
