# Generated by Django 4.0.4 on 2022-05-14 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_balance_customuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.FloatField(default=1000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баланс'),
        ),
    ]
