# Generated by Django 4.0.4 on 2022-05-07 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_name'),
        ('rating', '0002_alter_rating_company_alter_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='companies.company', verbose_name='Компания'),
        ),
    ]
