# Generated by Django 4.0.4 on 2022-05-13 15:39

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lot',
            managers=[
                ('lots', django.db.models.manager.Manager()),
            ],
        ),
    ]
