# Generated by Django 4.0.4 on 2022-05-13 15:39

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lot',
            managers=[
                ('lots', django.db.models.manager.Manager()),
            ],
        ),
    ]
