# Generated by Django 4.0.4 on 2022-05-14 17:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_lot_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shares',
            managers=[
                ('shares', django.db.models.manager.Manager()),
            ],
        ),
    ]
