# Generated by Django 4.0.4 on 2022-05-07 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_alter_company_options_alter_industry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='company',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='shareholders',
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(default='Другое', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='companies', to='companies.industry', verbose_name='Отрасль'),
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Акции')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Компания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Акционер')),
            ],
            options={
                'verbose_name': 'Акции',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.AddConstraint(
            model_name='shares',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='У одного пользователя может быть только одно хранилище акций одной компании.'),
        ),
    ]
