# Generated by Django 4.0.4 on 2022-05-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shares',
        ),
    ]
