# Generated by Django 4.0.4 on 2022-05-15 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0006_company_description_company_owners_company_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Владельцы'),
        ),
    ]
