# Generated by Django 4.0.4 on 2022-05-19 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0008_company_trust_points'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='company',
            managers=[
                ('companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='owners',
        ),
        migrations.AddField(
            model_name='company',
            name='stockholders',
            field=models.ManyToManyField(blank=True, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Акционеры'),
        ),
    ]
