# Generated by Django 4.0.4 on 2022-05-22 05:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_company_managers_remove_company_owners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='Эта компания ничего о себе не сказала, но мы уверены, что она очень хорошая!', help_text='Опишите компанию', max_length=1024, verbose_name='Описание'),
        ),
    ]
