# Generated by Django 4.0.4 on 2022-05-23 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_company_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='trust_points',
        ),
    ]
