# Generated by Django 4.0.4 on 2022-05-24 16:27

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_remove_company_trust_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[companies.models.validate_string], verbose_name='Название компании'),
        ),
    ]
